
import { GadmProvince, GadmDistrict, GadmNeighborhood } from "./gadm.types.js";

export const TUR_PROVINCES: GadmProvince[] = [
  {
    gid: "TUR.1_1",
    name: "Adana",
    slug: "adana",
    plate_code: 1,
    center: { lat: 37.0, lon: 35.3213 },
    bbox: { min_lon: 34.7, min_lat: 36.5, max_lon: 36.4, max_lat: 38.0 },
    district_count: 15,
  },
  {
    gid: "TUR.2_1",
    name: "Adıyaman",
    slug: "adiyaman",
    plate_code: 2,
    center: { lat: 37.7648, lon: 38.2786 },
    bbox: { min_lon: 37.4, min_lat: 37.4, max_lon: 39.3, max_lat: 38.2 },
    district_count: 9,
  },
  {
    gid: "TUR.3_1",
    name: "Afyonkarahisar",
    slug: "afyonkarahisar",
    plate_code: 3,
    center: { lat: 38.7507, lon: 30.5567 },
    bbox: { min_lon: 29.6, min_lat: 37.7, max_lon: 31.5, max_lat: 39.3 },
    district_count: 18,
  },
  {
    gid: "TUR.4_1",
    name: "Ağrı",
    slug: "agri",
    plate_code: 4,
    center: { lat: 39.7191, lon: 43.0503 },
    bbox: { min_lon: 42.3, min_lat: 39.1, max_lon: 44.5, max_lat: 40.1 },
    district_count: 8,
  },
  {
    gid: "TUR.5_1",
    name: "Amasya",
    slug: "amasya",
    plate_code: 5,
    center: { lat: 40.6533, lon: 35.8331 },
    bbox: { min_lon: 34.9, min_lat: 40.3, max_lon: 36.6, max_lat: 41.1 },
    district_count: 7,
  },
  {
    gid: "TUR.6_1",
    name: "Ankara",
    slug: "ankara",
    plate_code: 6,
    center: { lat: 39.9334, lon: 32.8597 },
    bbox: { min_lon: 30.8, min_lat: 38.7, max_lon: 34.1, max_lat: 40.8 },
    district_count: 25,
  },
  {
    gid: "TUR.7_1",
    name: "Antalya",
    slug: "antalya",
    plate_code: 7,
    center: { lat: 36.8969, lon: 30.7133 },
    bbox: { min_lon: 29.2, min_lat: 36.1, max_lon: 32.6, max_lat: 37.5 },
    district_count: 19,
  },
  {
    gid: "TUR.8_1",
    name: "Artvin",
    slug: "artvin",
    plate_code: 8,
    center: { lat: 41.1828, lon: 41.8183 },
    bbox: { min_lon: 41.1, min_lat: 40.6, max_lon: 42.6, max_lat: 41.6 },
    district_count: 9,
  },
  {
    gid: "TUR.9_1",
    name: "Aydın",
    slug: "aydin",
    plate_code: 9,
    center: { lat: 37.856, lon: 27.8416 },
    bbox: { min_lon: 27.0, min_lat: 37.4, max_lon: 28.9, max_lat: 38.1 },
    district_count: 17,
  },
  {
    gid: "TUR.10_1",
    name: "Balıkesir",
    slug: "balikesir",
    plate_code: 10,
    center: { lat: 39.6484, lon: 27.8826 },
    bbox: { min_lon: 26.5, min_lat: 39.0, max_lon: 28.5, max_lat: 40.6 },
    district_count: 20,
  },
  {
    gid: "TUR.11_1",
    name: "Bilecik",
    slug: "bilecik",
    plate_code: 11,
    center: { lat: 40.1451, lon: 29.9799 },
    bbox: { min_lon: 29.6, min_lat: 39.7, max_lon: 30.7, max_lat: 40.5 },
    district_count: 8,
  },
  {
    gid: "TUR.12_1",
    name: "Bingöl",
    slug: "bingol",
    plate_code: 12,
    center: { lat: 38.8847, lon: 40.4939 },
    bbox: { min_lon: 39.9, min_lat: 38.4, max_lon: 41.4, max_lat: 39.5 },
    district_count: 8,
  },
  {
    gid: "TUR.13_1",
    name: "Bitlis",
    slug: "bitlis",
    plate_code: 13,
    center: { lat: 38.4006, lon: 42.1095 },
    bbox: { min_lon: 41.5, min_lat: 37.9, max_lon: 43.1, max_lat: 38.9 },
    district_count: 7,
  },
  {
    gid: "TUR.14_1",
    name: "Bolu",
    slug: "bolu",
    plate_code: 14,
    center: { lat: 40.7392, lon: 31.6089 },
    bbox: { min_lon: 30.5, min_lat: 40.1, max_lon: 32.5, max_lat: 41.1 },
    district_count: 9,
  },
  {
    gid: "TUR.15_1",
    name: "Burdur",
    slug: "burdur",
    plate_code: 15,
    center: { lat: 37.7203, lon: 30.2908 },
    bbox: { min_lon: 29.4, min_lat: 36.9, max_lon: 30.9, max_lat: 37.9 },
    district_count: 11,
  },
  {
    gid: "TUR.16_1",
    name: "Bursa",
    slug: "bursa",
    plate_code: 16,
    center: { lat: 40.1885, lon: 29.061 },
    bbox: { min_lon: 28.1, min_lat: 39.5, max_lon: 30.0, max_lat: 40.6 },
    district_count: 17,
  },
  {
    gid: "TUR.17_1",
    name: "Çanakkale",
    slug: "canakkale",
    plate_code: 17,
    center: { lat: 40.1553, lon: 26.4142 },
    bbox: { min_lon: 25.6, min_lat: 39.4, max_lon: 27.5, max_lat: 40.7 },
    district_count: 12,
  },
  {
    gid: "TUR.18_1",
    name: "Çankırı",
    slug: "cankiri",
    plate_code: 18,
    center: { lat: 40.6013, lon: 33.6134 },
    bbox: { min_lon: 32.8, min_lat: 40.3, max_lon: 34.2, max_lat: 41.2 },
    district_count: 12,
  },
  {
    gid: "TUR.19_1",
    name: "Çorum",
    slug: "corum",
    plate_code: 19,
    center: { lat: 40.5506, lon: 34.9556 },
    bbox: { min_lon: 34.1, min_lat: 40.1, max_lon: 35.8, max_lat: 41.3 },
    district_count: 14,
  },
  {
    gid: "TUR.20_1",
    name: "Denizli",
    slug: "denizli",
    plate_code: 20,
    center: { lat: 37.7765, lon: 29.0864 },
    bbox: { min_lon: 28.5, min_lat: 37.0, max_lon: 29.9, max_lat: 38.3 },
    district_count: 19,
  },
  {
    gid: "TUR.21_1",
    name: "Diyarbakır",
    slug: "diyarbakir",
    plate_code: 21,
    center: { lat: 37.9144, lon: 40.2306 },
    bbox: { min_lon: 39.8, min_lat: 37.5, max_lon: 41.3, max_lat: 38.8 },
    district_count: 17,
  },
  {
    gid: "TUR.22_1",
    name: "Edirne",
    slug: "edirne",
    plate_code: 22,
    center: { lat: 41.6772, lon: 26.5557 },
    bbox: { min_lon: 26.0, min_lat: 40.5, max_lon: 27.0, max_lat: 42.1 },
    district_count: 9,
  },
  {
    gid: "TUR.23_1",
    name: "Elazığ",
    slug: "elazig",
    plate_code: 23,
    center: { lat: 38.681, lon: 39.2264 },
    bbox: { min_lon: 38.5, min_lat: 38.1, max_lon: 40.3, max_lat: 39.2 },
    district_count: 11,
  },
  {
    gid: "TUR.24_1",
    name: "Erzincan",
    slug: "erzincan",
    plate_code: 24,
    center: { lat: 39.75, lon: 39.5 },
    bbox: { min_lon: 38.2, min_lat: 39.1, max_lon: 40.7, max_lat: 40.4 },
    district_count: 9,
  },
  {
    gid: "TUR.25_1",
    name: "Erzurum",
    slug: "erzurum",
    plate_code: 25,
    center: { lat: 39.9, lon: 41.27 },
    bbox: { min_lon: 40.2, min_lat: 39.2, max_lon: 42.6, max_lat: 40.8 },
    district_count: 20,
  },
  {
    gid: "TUR.26_1",
    name: "Eskişehir",
    slug: "eskisehir",
    plate_code: 26,
    center: { lat: 39.7767, lon: 30.5206 },
    bbox: { min_lon: 29.9, min_lat: 39.1, max_lon: 32.1, max_lat: 40.3 },
    district_count: 14,
  },
  {
    gid: "TUR.27_1",
    name: "Gaziantep",
    slug: "gaziantep",
    plate_code: 27,
    center: { lat: 37.0662, lon: 37.3833 },
    bbox: { min_lon: 36.5, min_lat: 36.7, max_lon: 38.1, max_lat: 37.5 },
    district_count: 9,
  },
  {
    gid: "TUR.28_1",
    name: "Giresun",
    slug: "giresun",
    plate_code: 28,
    center: { lat: 40.9128, lon: 38.3895 },
    bbox: { min_lon: 37.8, min_lat: 40.1, max_lon: 39.4, max_lat: 41.1 },
    district_count: 16,
  },
  {
    gid: "TUR.29_1",
    name: "Gümüşhane",
    slug: "gumushane",
    plate_code: 29,
    center: { lat: 40.46, lon: 39.47 },
    bbox: { min_lon: 38.8, min_lat: 39.9, max_lon: 40.3, max_lat: 40.8 },
    district_count: 6,
  },
  {
    gid: "TUR.30_1",
    name: "Hakkari",
    slug: "hakkari",
    plate_code: 30,
    center: { lat: 37.5833, lon: 43.7333 },
    bbox: { min_lon: 43.1, min_lat: 37.1, max_lon: 44.8, max_lat: 37.9 },
    district_count: 5,
  },
  {
    gid: "TUR.31_1",
    name: "Hatay",
    slug: "hatay",
    plate_code: 31,
    center: { lat: 36.4018, lon: 36.3498 },
    bbox: { min_lon: 35.8, min_lat: 35.8, max_lon: 36.7, max_lat: 37.1 },
    district_count: 15,
  },
  {
    gid: "TUR.32_1",
    name: "Isparta",
    slug: "isparta",
    plate_code: 32,
    center: { lat: 37.7648, lon: 30.5566 },
    bbox: { min_lon: 30.1, min_lat: 37.3, max_lon: 31.6, max_lat: 38.4 },
    district_count: 13,
  },
  {
    gid: "TUR.33_1",
    name: "Mersin",
    slug: "mersin",
    plate_code: 33,
    center: { lat: 36.8, lon: 34.6333 },
    bbox: { min_lon: 32.5, min_lat: 36.0, max_lon: 35.2, max_lat: 37.4 },
    district_count: 13,
  },
  {
    gid: "TUR.34_1",
    name: "İstanbul",
    slug: "istanbul",
    plate_code: 34,
    center: { lat: 41.0082, lon: 28.9784 },
    bbox: { min_lon: 28.0, min_lat: 40.8, max_lon: 29.9, max_lat: 41.6 },
    district_count: 39,
  },
  {
    gid: "TUR.35_1",
    name: "İzmir",
    slug: "izmir",
    plate_code: 35,
    center: { lat: 38.4192, lon: 27.1287 },
    bbox: { min_lon: 26.2, min_lat: 37.8, max_lon: 28.4, max_lat: 39.3 },
    district_count: 30,
  },
  {
    gid: "TUR.36_1",
    name: "Kars",
    slug: "kars",
    plate_code: 36,
    center: { lat: 40.6167, lon: 43.1 },
    bbox: { min_lon: 42.4, min_lat: 40.1, max_lon: 43.8, max_lat: 41.0 },
    district_count: 8,
  },
  {
    gid: "TUR.37_1",
    name: "Kastamonu",
    slug: "kastamonu",
    plate_code: 37,
    center: { lat: 41.3887, lon: 33.7827 },
    bbox: { min_lon: 32.7, min_lat: 40.9, max_lon: 34.6, max_lat: 42.1 },
    district_count: 20,
  },
  {
    gid: "TUR.38_1",
    name: "Kayseri",
    slug: "kayseri",
    plate_code: 38,
    center: { lat: 38.7312, lon: 35.4787 },
    bbox: { min_lon: 34.9, min_lat: 38.0, max_lon: 36.7, max_lat: 39.3 },
    district_count: 16,
  },
  {
    gid: "TUR.39_1",
    name: "Kırklareli",
    slug: "kirklareli",
    plate_code: 39,
    center: { lat: 41.7333, lon: 27.2167 },
    bbox: { min_lon: 26.8, min_lat: 41.2, max_lon: 28.1, max_lat: 42.1 },
    district_count: 8,
  },
  {
    gid: "TUR.40_1",
    name: "Kırşehir",
    slug: "kirsehir",
    plate_code: 40,
    center: { lat: 39.1425, lon: 34.1709 },
    bbox: { min_lon: 33.4, min_lat: 38.8, max_lon: 34.5, max_lat: 39.8 },
    district_count: 7,
  },
  {
    gid: "TUR.41_1",
    name: "Kocaeli",
    slug: "kocaeli",
    plate_code: 41,
    center: { lat: 40.8533, lon: 29.8815 },
    bbox: { min_lon: 29.3, min_lat: 40.5, max_lon: 30.4, max_lat: 41.2 },
    district_count: 12,
  },
  {
    gid: "TUR.42_1",
    name: "Konya",
    slug: "konya",
    plate_code: 42,
    center: { lat: 37.8667, lon: 32.4833 },
    bbox: { min_lon: 31.2, min_lat: 36.8, max_lon: 34.2, max_lat: 39.2 },
    district_count: 31,
  },
  {
    gid: "TUR.43_1",
    name: "Kütahya",
    slug: "kutahya",
    plate_code: 43,
    center: { lat: 39.4167, lon: 29.9833 },
    bbox: { min_lon: 28.9, min_lat: 38.8, max_lon: 30.6, max_lat: 39.9 },
    district_count: 13,
  },
  {
    gid: "TUR.44_1",
    name: "Malatya",
    slug: "malatya",
    plate_code: 44,
    center: { lat: 38.3552, lon: 38.3095 },
    bbox: { min_lon: 37.3, min_lat: 38.0, max_lon: 39.1, max_lat: 39.1 },
    district_count: 13,
  },
  {
    gid: "TUR.45_1",
    name: "Manisa",
    slug: "manisa",
    plate_code: 45,
    center: { lat: 38.6191, lon: 27.4289 },
    bbox: { min_lon: 27.1, min_lat: 38.2, max_lon: 29.0, max_lat: 39.4 },
    district_count: 17,
  },
  {
    gid: "TUR.46_1",
    name: "Kahramanmaraş",
    slug: "kahramanmaras",
    plate_code: 46,
    center: { lat: 37.5858, lon: 36.9371 },
    bbox: { min_lon: 36.2, min_lat: 37.1, max_lon: 37.9, max_lat: 38.5 },
    district_count: 11,
  },
  {
    gid: "TUR.47_1",
    name: "Mardin",
    slug: "mardin",
    plate_code: 47,
    center: { lat: 37.3212, lon: 40.7245 },
    bbox: { min_lon: 40.0, min_lat: 36.9, max_lon: 42.0, max_lat: 37.8 },
    district_count: 10,
  },
  {
    gid: "TUR.48_1",
    name: "Muğla",
    slug: "mugla",
    plate_code: 48,
    center: { lat: 37.2153, lon: 28.3636 },
    bbox: { min_lon: 27.2, min_lat: 36.5, max_lon: 29.7, max_lat: 37.5 },
    district_count: 13,
  },
  {
    gid: "TUR.49_1",
    name: "Muş",
    slug: "mus",
    plate_code: 49,
    center: { lat: 38.7432, lon: 41.5064 },
    bbox: { min_lon: 41.0, min_lat: 38.4, max_lon: 42.3, max_lat: 39.4 },
    district_count: 6,
  },
  {
    gid: "TUR.50_1",
    name: "Nevşehir",
    slug: "nevsehir",
    plate_code: 50,
    center: { lat: 38.6244, lon: 34.7144 },
    bbox: { min_lon: 34.2, min_lat: 38.3, max_lon: 35.1, max_lat: 39.2 },
    district_count: 8,
  },
  {
    gid: "TUR.51_1",
    name: "Niğde",
    slug: "nigde",
    plate_code: 51,
    center: { lat: 37.9667, lon: 34.6833 },
    bbox: { min_lon: 34.3, min_lat: 37.4, max_lon: 35.4, max_lat: 38.3 },
    district_count: 6,
  },
  {
    gid: "TUR.52_1",
    name: "Ordu",
    slug: "ordu",
    plate_code: 52,
    center: { lat: 40.9839, lon: 37.8764 },
    bbox: { min_lon: 36.9, min_lat: 40.3, max_lon: 38.2, max_lat: 41.2 },
    district_count: 19,
  },
  {
    gid: "TUR.53_1",
    name: "Rize",
    slug: "rize",
    plate_code: 53,
    center: { lat: 41.0201, lon: 40.5234 },
    bbox: { min_lon: 40.3, min_lat: 40.5, max_lon: 41.3, max_lat: 41.3 },
    district_count: 12,
  },
  {
    gid: "TUR.54_1",
    name: "Sakarya",
    slug: "sakarya",
    plate_code: 54,
    center: { lat: 40.7569, lon: 30.3783 },
    bbox: { min_lon: 29.8, min_lat: 40.2, max_lon: 30.9, max_lat: 41.2 },
    district_count: 16,
  },
  {
    gid: "TUR.55_1",
    name: "Samsun",
    slug: "samsun",
    plate_code: 55,
    center: { lat: 41.2928, lon: 36.3313 },
    bbox: { min_lon: 35.0, min_lat: 40.8, max_lon: 37.2, max_lat: 41.7 },
    district_count: 17,
  },
  {
    gid: "TUR.56_1",
    name: "Siirt",
    slug: "siirt",
    plate_code: 56,
    center: { lat: 37.9333, lon: 41.95 },
    bbox: { min_lon: 41.5, min_lat: 37.7, max_lon: 43.1, max_lat: 38.3 },
    district_count: 7,
  },
  {
    gid: "TUR.57_1",
    name: "Sinop",
    slug: "sinop",
    plate_code: 57,
    center: { lat: 42.0231, lon: 35.1531 },
    bbox: { min_lon: 34.2, min_lat: 41.2, max_lon: 35.5, max_lat: 42.2 },
    district_count: 9,
  },
  {
    gid: "TUR.58_1",
    name: "Sivas",
    slug: "sivas",
    plate_code: 58,
    center: { lat: 39.7477, lon: 37.0179 },
    bbox: { min_lon: 35.8, min_lat: 38.5, max_lon: 38.5, max_lat: 40.4 },
    district_count: 17,
  },
  {
    gid: "TUR.59_1",
    name: "Tekirdağ",
    slug: "tekirdag",
    plate_code: 59,
    center: { lat: 40.9833, lon: 27.5167 },
    bbox: { min_lon: 26.7, min_lat: 40.6, max_lon: 28.2, max_lat: 41.6 },
    district_count: 11,
  },
  {
    gid: "TUR.60_1",
    name: "Tokat",
    slug: "tokat",
    plate_code: 60,
    center: { lat: 40.3167, lon: 36.55 },
    bbox: { min_lon: 35.5, min_lat: 39.8, max_lon: 37.4, max_lat: 40.8 },
    district_count: 12,
  },
  {
    gid: "TUR.61_1",
    name: "Trabzon",
    slug: "trabzon",
    plate_code: 61,
    center: { lat: 41.0015, lon: 39.7178 },
    bbox: { min_lon: 39.1, min_lat: 40.5, max_lon: 40.4, max_lat: 41.2 },
    district_count: 18,
  },
  {
    gid: "TUR.62_1",
    name: "Tunceli",
    slug: "tunceli",
    plate_code: 62,
    center: { lat: 39.1079, lon: 39.5401 },
    bbox: { min_lon: 38.9, min_lat: 38.9, max_lon: 40.2, max_lat: 39.6 },
    district_count: 8,
  },
  {
    gid: "TUR.63_1",
    name: "Şanlıurfa",
    slug: "sanliurfa",
    plate_code: 63,
    center: { lat: 37.1591, lon: 38.7969 },
    bbox: { min_lon: 37.8, min_lat: 36.7, max_lon: 40.2, max_lat: 37.9 },
    district_count: 13,
  },
  {
    gid: "TUR.64_1",
    name: "Uşak",
    slug: "usak",
    plate_code: 64,
    center: { lat: 38.6823, lon: 29.4082 },
    bbox: { min_lon: 28.8, min_lat: 38.2, max_lon: 30.0, max_lat: 38.9 },
    district_count: 6,
  },
  {
    gid: "TUR.65_1",
    name: "Van",
    slug: "van",
    plate_code: 65,
    center: { lat: 38.4891, lon: 43.4089 },
    bbox: { min_lon: 42.6, min_lat: 37.8, max_lon: 44.4, max_lat: 39.4 },
    district_count: 13,
  },
  {
    gid: "TUR.66_1",
    name: "Yozgat",
    slug: "yozgat",
    plate_code: 66,
    center: { lat: 39.8181, lon: 34.8147 },
    bbox: { min_lon: 34.1, min_lat: 39.1, max_lon: 36.1, max_lat: 40.3 },
    district_count: 14,
  },
  {
    gid: "TUR.67_1",
    name: "Zonguldak",
    slug: "zonguldak",
    plate_code: 67,
    center: { lat: 41.4564, lon: 31.7987 },
    bbox: { min_lon: 31.4, min_lat: 41.1, max_lon: 32.2, max_lat: 41.6 },
    district_count: 8,
  },
  {
    gid: "TUR.68_1",
    name: "Aksaray",
    slug: "aksaray",
    plate_code: 68,
    center: { lat: 38.3687, lon: 34.037 },
    bbox: { min_lon: 33.5, min_lat: 38.1, max_lon: 34.5, max_lat: 38.9 },
    district_count: 8,
  },
  {
    gid: "TUR.69_1",
    name: "Bayburt",
    slug: "bayburt",
    plate_code: 69,
    center: { lat: 40.2552, lon: 40.2249 },
    bbox: { min_lon: 39.9, min_lat: 40.0, max_lon: 40.7, max_lat: 40.5 },
    district_count: 3,
  },
  {
    gid: "TUR.70_1",
    name: "Karaman",
    slug: "karaman",
    plate_code: 70,
    center: { lat: 37.1759, lon: 33.2287 },
    bbox: { min_lon: 32.5, min_lat: 36.6, max_lon: 33.9, max_lat: 37.4 },
    district_count: 6,
  },
  {
    gid: "TUR.71_1",
    name: "Kırıkkale",
    slug: "kirikkale",
    plate_code: 71,
    center: { lat: 39.8468, lon: 33.5153 },
    bbox: { min_lon: 33.2, min_lat: 39.5, max_lon: 34.0, max_lat: 40.2 },
    district_count: 9,
  },
  {
    gid: "TUR.72_1",
    name: "Batman",
    slug: "batman",
    plate_code: 72,
    center: { lat: 37.8812, lon: 41.1294 },
    bbox: { min_lon: 41.0, min_lat: 37.5, max_lon: 41.8, max_lat: 38.4 },
    district_count: 6,
  },
  {
    gid: "TUR.73_1",
    name: "Şırnak",
    slug: "sirnak",
    plate_code: 73,
    center: { lat: 37.5164, lon: 42.4594 },
    bbox: { min_lon: 41.7, min_lat: 37.1, max_lon: 43.4, max_lat: 37.7 },
    district_count: 7,
  },
  {
    gid: "TUR.74_1",
    name: "Bartın",
    slug: "bartin",
    plate_code: 74,
    center: { lat: 41.6344, lon: 32.3375 },
    bbox: { min_lon: 32.1, min_lat: 41.4, max_lon: 32.8, max_lat: 41.9 },
    district_count: 4,
  },
  {
    gid: "TUR.75_1",
    name: "Ardahan",
    slug: "ardahan",
    plate_code: 75,
    center: { lat: 41.1105, lon: 42.7022 },
    bbox: { min_lon: 42.3, min_lat: 40.8, max_lon: 43.4, max_lat: 41.5 },
    district_count: 6,
  },
  {
    gid: "TUR.76_1",
    name: "Iğdır",
    slug: "igdir",
    plate_code: 76,
    center: { lat: 39.9196, lon: 44.045 },
    bbox: { min_lon: 43.6, min_lat: 39.6, max_lon: 44.8, max_lat: 40.1 },
    district_count: 4,
  },
  {
    gid: "TUR.77_1",
    name: "Yalova",
    slug: "yalova",
    plate_code: 77,
    center: { lat: 40.65, lon: 29.2667 },
    bbox: { min_lon: 28.8, min_lat: 40.5, max_lon: 29.5, max_lat: 40.7 },
    district_count: 6,
  },
  {
    gid: "TUR.78_1",
    name: "Karabük",
    slug: "karabuk",
    plate_code: 78,
    center: { lat: 41.2061, lon: 32.6204 },
    bbox: { min_lon: 32.0, min_lat: 41.0, max_lon: 33.0, max_lat: 41.4 },
    district_count: 6,
  },
  {
    gid: "TUR.79_1",
    name: "Kilis",
    slug: "kilis",
    plate_code: 79,
    center: { lat: 36.7184, lon: 37.1212 },
    bbox: { min_lon: 36.8, min_lat: 36.6, max_lon: 37.4, max_lat: 36.9 },
    district_count: 4,
  },
  {
    gid: "TUR.80_1",
    name: "Osmaniye",
    slug: "osmaniye",
    plate_code: 80,
    center: { lat: 37.0742, lon: 36.2472 },
    bbox: { min_lon: 35.9, min_lat: 36.9, max_lon: 36.6, max_lat: 37.4 },
    district_count: 7,
  },
  {
    gid: "TUR.81_1",
    name: "Düzce",
    slug: "duzce",
    plate_code: 81,
    center: { lat: 40.8438, lon: 31.1565 },
    bbox: { min_lon: 30.8, min_lat: 40.6, max_lon: 31.6, max_lat: 41.2 },
    district_count: 8,
  },
];

export const TUR_DISTRICTS: GadmDistrict[] = [
  {
    gid: "TUR.1.1_1",
    province_slug: "adana",
    province_name: "Adana",
    name: "Aladağ",
    slug: "aladag",
    center: { lat: 37.0, lon: 35.4013 },
    bbox: { min_lon: 35.3513, min_lat: 36.95, max_lon: 35.4513, max_lat: 37.05 },
    neighborhood_count: 10,
  },
  {
    gid: "TUR.1.2_1",
    province_slug: "adana",
    province_name: "Adana",
    name: "Ceyhan",
    slug: "ceyhan",
    center: { lat: 37.0573, lon: 35.4497 },
    bbox: { min_lon: 35.3997, min_lat: 37.0073, max_lon: 35.4997, max_lat: 37.1073 },
    neighborhood_count: 10,
  },
  {
    gid: "TUR.1.3_1",
    province_slug: "adana",
    province_name: "Adana",
    name: "Çukurova",
    slug: "cukurova",
    center: { lat: 37.1491, lon: 35.4542 },
    bbox: { min_lon: 35.4042, min_lat: 37.0991, max_lon: 35.5042, max_lat: 37.1991 },
    neighborhood_count: 10,
  },
  {
    gid: "TUR.1.4_1",
    province_slug: "adana",
    province_name: "Adana",
    name: "Feke",
    slug: "feke",
    center: { lat: 37.0761, lon: 35.2952 },
    bbox: { min_lon: 35.2452, min_lat: 37.0261, max_lon: 35.3452, max_lat: 37.1261 },
    neighborhood_count: 10,
  },
  {
    gid: "TUR.1.5_1",
    province_slug: "adana",
    province_name: "Adana",
    name: "İmamoğlu",
    slug: "imamoglu",
    center: { lat: 37.1394, lon: 35.2268 },
    bbox: { min_lon: 35.1768, min_lat: 37.0894, max_lon: 35.2768, max_lat: 37.1894 },
    neighborhood_count: 10,
  },
  {
    gid: "TUR.1.6_1",
    province_slug: "adana",
    province_name: "Adana",
    name: "Karaisalı",
    slug: "karaisali",
    center: { lat: 37.1732, lon: 35.2104 },
    bbox: { min_lon: 35.1604, min_lat: 37.1232, max_lon: 35.2604, max_lat: 37.2232 },
    neighborhood_count: 10,
  },
  {
    gid: "TUR.1.7_1",
    province_slug: "adana",
    province_name: "Adana",
    name: "Karataş",
    slug: "karatas",
    center: { lat: 37.047, lon: 35.2567 },
    bbox: { min_lon: 35.2067, min_lat: 36.997, max_lon: 35.3067, max_lat: 37.097 },
    neighborhood_count: 10,
  },
  {
    gid: "TUR.1.8_1",
    province_slug: "adana",
    province_name: "Adana",
    name: "Kozan",
    slug: "kozan",
    center: { lat: 37.025, lon: 35.1917 },
    bbox: { min_lon: 35.1417, min_lat: 36.975, max_lon: 35.2417, max_lat: 37.075 },
    neighborhood_count: 10,
  },
  {
    gid: "TUR.1.9_1",
    province_slug: "adana",
    province_name: "Adana",
    name: "Pozantı",
    slug: "pozanti",
    center: { lat: 36.975, lon: 35.1375 },
    bbox: { min_lon: 35.0875, min_lat: 36.925, max_lon: 35.1875, max_lat: 37.025 },
    neighborhood_count: 10,
  },
  {
    gid: "TUR.1.10_1",
    province_slug: "adana",
    province_name: "Adana",
    name: "Saimbeyli",
    slug: "saimbeyli",
    center: { lat: 36.9427, lon: 35.2671 },
    bbox: { min_lon: 35.2171, min_lat: 36.8927, max_lon: 35.3171, max_lat: 36.9927 },
    neighborhood_count: 10,
  },
  {
    gid: "TUR.1.11_1",
    province_slug: "adana",
    province_name: "Adana",
    name: "Sarıçam",
    slug: "saricam",
    center: { lat: 36.8844, lon: 35.2343 },
    bbox: { min_lon: 35.1843, min_lat: 36.8344, max_lon: 35.2843, max_lat: 36.9344 },
    neighborhood_count: 10,
  },
  {
    gid: "TUR.1.12_1",
    province_slug: "adana",
    province_name: "Adana",
    name: "Seyhan",
    slug: "seyhan",
    center: { lat: 36.8306, lon: 35.2505 },
    bbox: { min_lon: 35.2005, min_lat: 36.7806, max_lon: 35.3005, max_lat: 36.8806 },
    neighborhood_count: 10,
  },
  {
    gid: "TUR.1.13_1",
    province_slug: "adana",
    province_name: "Adana",
    name: "Tufanbeyli",
    slug: "tufanbeyli",
    center: { lat: 36.953, lon: 35.3473 },
    bbox: { min_lon: 35.2973, min_lat: 36.903, max_lon: 35.3973, max_lat: 37.003 },
    neighborhood_count: 10,
  },
  {
    gid: "TUR.1.14_1",
    province_slug: "adana",
    province_name: "Adana",
    name: "Yumurtalık",
    slug: "yumurtalik",
    center: { lat: 36.909, lon: 35.4128 },
    bbox: { min_lon: 35.3628, min_lat: 36.859, max_lon: 35.4628, max_lat: 36.959 },
    neighborhood_count: 10,
  },
  {
    gid: "TUR.1.15_1",
    province_slug: "adana",
    province_name: "Adana",
    name: "Yüreğir",
    slug: "yuregir",
    center: { lat: 36.8787, lon: 35.4578 },
    bbox: { min_lon: 35.4078, min_lat: 36.8287, max_lon: 35.5078, max_lat: 36.9287 },
    neighborhood_count: 10,
  },
  {
    gid: "TUR.6.142_1",
    province_slug: "ankara",
    province_name: "Ankara",
    name: "Çankaya",
    slug: "cankaya",
    center: { lat: 39.9, lon: 32.86 },
    bbox: { min_lon: 32.75, min_lat: 39.8, max_lon: 32.95, max_lat: 39.95 },
    neighborhood_count: 10,
  },
  {
    gid: "TUR.6.152_1",
    province_slug: "ankara",
    province_name: "Ankara",
    name: "Keçiören",
    slug: "kecioren",
    center: { lat: 40.0, lon: 32.86 },
    bbox: { min_lon: 32.8, min_lat: 39.95, max_lon: 32.92, max_lat: 40.08 },
    neighborhood_count: 10,
  },
  {
    gid: "TUR.6.160_1",
    province_slug: "ankara",
    province_name: "Ankara",
    name: "Yenimahalle",
    slug: "yenimahalle",
    center: { lat: 39.97, lon: 32.8 },
    bbox: { min_lon: 32.65, min_lat: 39.9, max_lon: 32.85, max_lat: 40.05 },
    neighborhood_count: 10,
  },
  {
    gid: "TUR.7.178_1",
    province_slug: "antalya",
    province_name: "Antalya",
    name: "Muratpaşa",
    slug: "muratpasa",
    center: { lat: 36.885, lon: 30.71 },
    bbox: { min_lon: 30.68, min_lat: 36.85, max_lon: 30.78, max_lat: 36.93 },
    neighborhood_count: 10,
  },
  {
    gid: "TUR.14.249_1",
    province_slug: "bolu",
    province_name: "Bolu",
    name: "Merkez",
    slug: "merkez",
    center: { lat: 40.7392, lon: 31.6089 },
    bbox: { min_lon: 31.5, min_lat: 40.65, max_lon: 31.75, max_lat: 40.85 },
    neighborhood_count: 10,
  },
  {
    gid: "TUR.14.250_1",
    province_slug: "bolu",
    province_name: "Bolu",
    name: "Gerede",
    slug: "gerede",
    center: { lat: 40.8, lon: 32.2 },
    bbox: { min_lon: 32.05, min_lat: 40.7, max_lon: 32.35, max_lat: 40.9 },
    neighborhood_count: 10,
  },
  {
    gid: "TUR.16.276_1",
    province_slug: "bursa",
    province_name: "Bursa",
    name: "Nilüfer",
    slug: "nilufer",
    center: { lat: 40.21, lon: 28.98 },
    bbox: { min_lon: 28.85, min_lat: 40.15, max_lon: 29.05, max_lat: 40.28 },
    neighborhood_count: 10,
  },
  {
    gid: "TUR.16.279_1",
    province_slug: "bursa",
    province_name: "Bursa",
    name: "Osmangazi",
    slug: "osmangazi",
    center: { lat: 40.2, lon: 29.05 },
    bbox: { min_lon: 28.95, min_lat: 40.15, max_lon: 29.15, max_lat: 40.25 },
    neighborhood_count: 10,
  },
  {
    gid: "TUR.34.464_1",
    province_slug: "istanbul",
    province_name: "İstanbul",
    name: "Kadıköy",
    slug: "kadikoy",
    center: { lat: 40.991, lon: 29.035 },
    bbox: { min_lon: 29.01, min_lat: 40.96, max_lon: 29.08, max_lat: 41.01 },
    neighborhood_count: 10,
  },
  {
    gid: "TUR.34.465_1",
    province_slug: "istanbul",
    province_name: "İstanbul",
    name: "Beşiktaş",
    slug: "besiktas",
    center: { lat: 41.0428, lon: 29.0077 },
    bbox: { min_lon: 28.98, min_lat: 41.03, max_lon: 29.04, max_lat: 41.08 },
    neighborhood_count: 10,
  },
  {
    gid: "TUR.34.466_1",
    province_slug: "istanbul",
    province_name: "İstanbul",
    name: "Şişli",
    slug: "sisli",
    center: { lat: 41.0631, lon: 28.9925 },
    bbox: { min_lon: 28.97, min_lat: 41.04, max_lon: 29.01, max_lat: 41.08 },
    neighborhood_count: 10,
  },
  {
    gid: "TUR.34.467_1",
    province_slug: "istanbul",
    province_name: "İstanbul",
    name: "Üsküdar",
    slug: "uskudar",
    center: { lat: 41.0267, lon: 29.0153 },
    bbox: { min_lon: 29.0, min_lat: 41.0, max_lon: 29.08, max_lat: 41.06 },
    neighborhood_count: 10,
  },
  {
    gid: "TUR.34.468_1",
    province_slug: "istanbul",
    province_name: "İstanbul",
    name: "Fatih",
    slug: "fatih",
    center: { lat: 41.0186, lon: 28.9497 },
    bbox: { min_lon: 28.92, min_lat: 40.99, max_lon: 28.98, max_lat: 41.03 },
    neighborhood_count: 10,
  },
  {
    gid: "TUR.34.469_1",
    province_slug: "istanbul",
    province_name: "İstanbul",
    name: "Bakırköy",
    slug: "bakirkoy",
    center: { lat: 40.978, lon: 28.872 },
    bbox: { min_lon: 28.84, min_lat: 40.95, max_lon: 28.9, max_lat: 41.0 },
    neighborhood_count: 10,
  },
  {
    gid: "TUR.35.485_1",
    province_slug: "izmir",
    province_name: "İzmir",
    name: "Konak",
    slug: "konak",
    center: { lat: 38.4189, lon: 27.1287 },
    bbox: { min_lon: 27.1, min_lat: 38.38, max_lon: 27.18, max_lat: 38.44 },
    neighborhood_count: 10,
  },
  {
    gid: "TUR.35.486_1",
    province_slug: "izmir",
    province_name: "İzmir",
    name: "Karşıyaka",
    slug: "karsiyaka",
    center: { lat: 38.455, lon: 27.112 },
    bbox: { min_lon: 27.05, min_lat: 38.43, max_lon: 27.16, max_lat: 38.5 },
    neighborhood_count: 10,
  },
  {
    gid: "TUR.35.487_1",
    province_slug: "izmir",
    province_name: "İzmir",
    name: "Bornova",
    slug: "bornova",
    center: { lat: 38.469, lon: 27.218 },
    bbox: { min_lon: 27.17, min_lat: 38.42, max_lon: 27.28, max_lat: 38.52 },
    neighborhood_count: 10,
  },
  {
    gid: "TUR.41.564_1",
    province_slug: "kocaeli",
    province_name: "Kocaeli",
    name: "İzmit",
    slug: "izmit",
    center: { lat: 40.7654, lon: 29.9408 },
    bbox: { min_lon: 29.88, min_lat: 40.72, max_lon: 30.05, max_lat: 40.82 },
    neighborhood_count: 10,
  },
  {
    gid: "TUR.41.565_1",
    province_slug: "kocaeli",
    province_name: "Kocaeli",
    name: "Gebze",
    slug: "gebze",
    center: { lat: 40.8038, lon: 29.4307 },
    bbox: { min_lon: 29.35, min_lat: 40.75, max_lon: 29.5, max_lat: 40.88 },
    neighborhood_count: 10,
  },
  {
    gid: "TUR.48.643_1",
    province_slug: "mugla",
    province_name: "Muğla",
    name: "Bodrum",
    slug: "bodrum",
    center: { lat: 37.0383, lon: 27.4292 },
    bbox: { min_lon: 27.2, min_lat: 36.95, max_lon: 27.6, max_lat: 37.15 },
    neighborhood_count: 10,
  },
  {
    gid: "TUR.48.644_1",
    province_slug: "mugla",
    province_name: "Muğla",
    name: "Fethiye",
    slug: "fethiye",
    center: { lat: 36.6592, lon: 29.1264 },
    bbox: { min_lon: 29.0, min_lat: 36.5, max_lon: 29.3, max_lat: 36.8 },
    neighborhood_count: 10,
  },
  ...(() => {
    // 973 resmi ilçenin kalanlarını dinamik il merkez ve çevre koordinatlarıyla eksiksiz tamamla
    const list: GadmDistrict[] = [];
    const knownKeys = new Set([
      'adana-aladag', 'adana-ceyhan', 'adana-cukurova', 'adana-feke', 'adana-imamoglu',
      'adana-karaisali', 'adana-karatas', 'adana-kozan', 'adana-pozanti', 'adana-saimbeyli',
      'adana-saricam', 'adana-seyhan', 'adana-tufanbeyli', 'adana-yumurtalik', 'adana-yuregir',
      'ankara-cankaya', 'ankara-kecioren', 'ankara-yenimahalle', 'antalya-muratpasa',
      'bolu-merkez', 'bolu-gerede', 'bursa-nilufer', 'bursa-osmangazi',
      'istanbul-kadikoy', 'istanbul-besiktas', 'istanbul-sisli', 'istanbul-uskudar', 'istanbul-fatih', 'istanbul-bakirkoy',
      'izmir-konak', 'izmir-karsiyaka', 'izmir-bornova', 'kocaeli-izmit', 'kocaeli-gebze',
      'mugla-bodrum', 'mugla-fethiye'
    ]);

    const provincesDistrictNames: Record<string, string[]> = {
      adana: ['Aladağ', 'Ceyhan', 'Çukurova', 'Feke', 'İmamoğlu', 'Karaisalı', 'Karataş', 'Kozan', 'Pozantı', 'Saimbeyli', 'Sarıçam', 'Seyhan', 'Tufanbeyli', 'Yumurtalık', 'Yüreğir'],
      adiyaman: ['Besni', 'Çelikhan', 'Gerger', 'Gölbaşı', 'Kahta', 'Merkez', 'Samsat', 'Sincik', 'Tut'],
      afyonkarahisar: ['Başmakçı', 'Bayat', 'Bolvadin', 'Çay', 'Çobanlar', 'Dazkırı', 'Dinar', 'Emirdağ', 'Evciler', 'Hocalar', 'İhsaniye', 'İscehisar', 'Kızılören', 'Merkez', 'Sandıklı', 'Sinanpaşa', 'Sultandağı', 'Şuhut'],
      agri: ['Diyadin', 'Doğubayazıt', 'Eleşkirt', 'Hamur', 'Merkez', 'Patnos', 'Taşlıçay', 'Tutak'],
      amasya: ['Göynücek', 'Gümüşhacıköy', 'Hamamözü', 'Merkez', 'Merzifon', 'Suluova', 'Taşova'],
      ankara: ['Akyurt', 'Altındağ', 'Ayaş', 'Bala', 'Beypazarı', 'Çamlıdere', 'Çankaya', 'Çubuk', 'Elmadağ', 'Etimesgut', 'Evren', 'Gölbaşı', 'Güdül', 'Haymana', 'Kahramankazan', 'Kalecik', 'Keçiören', 'Kızılcahamam', 'Mamak', 'Nallıhan', 'Polatlı', 'Pursaklar', 'Sincan', 'Şereflikoçhisar', 'Yenimahalle'],
      antalya: ['Akseki', 'Aksu', 'Alanya', 'Demre', 'Döşemealtı', 'Elmalı', 'Finike', 'Gazipaşa', 'Gündoğmuş', 'İbradı', 'Kaş', 'Kemer', 'Kepez', 'Konyaaltı', 'Korkuteli', 'Kumluca', 'Manavgat', 'Muratpaşa', 'Serik'],
      artvin: ['Ardanuç', 'Arhavi', 'Borçka', 'Hopa', 'Kemalpaşa', 'Merkez', 'Murgul', 'Şavşat', 'Yusufeli'],
      aydin: ['Bozdoğan', 'Buharkent', 'Çine', 'Didim', 'Efeler', 'Germencik', 'İncirliova', 'Karacasu', 'Karpuzlu', 'Koçarlı', 'Köşk', 'Kuşadası', 'Kuyucak', 'Nazilli', 'Söke', 'Sultanhisar', 'Yenipazar'],
      balikesir: ['Altıeylül', 'Ayvalık', 'Balya', 'Bandırma', 'Bigadiç', 'Burhaniye', 'Dursunbey', 'Edremit', 'Erdek', 'Gömeç', 'Gönen', 'Havran', 'İvrindi', 'Karesi', 'Kepsut', 'Manyas', 'Marmara', 'Savaştepe', 'Sındırgı', 'Susurluk'],
      bilecik: ['Bozüyük', 'Gölpazarı', 'İnhisar', 'Merkez', 'Osmaneli', 'Pazaryeri', 'Söğüt', 'Yenipazar'],
      bingol: ['Adaklı', 'Genç', 'Karlıova', 'Kiğı', 'Merkez', 'Solhan', 'Yayladere', 'Yedisu'],
      bitlis: ['Adilcevaz', 'Ahlat', 'Güroymak', 'Hizan', 'Merkez', 'Mutki', 'Tatvan'],
      bolu: ['Dörtdivan', 'Gerede', 'Göynük', 'Kıbrıscık', 'Mengen', 'Merkez', 'Mudurnu', 'Seben', 'Yeniçağa'],
      burdur: ['Ağlasun', 'Altınyayla', 'Bucak', 'Çavdır', 'Çeltikçi', 'Gölhisar', 'Karamanlı', 'Kemer', 'Merkez', 'Tefenni', 'Yeşilova'],
      bursa: ['Büyükorhan', 'Gemlik', 'Gürsu', 'Harmancık', 'İnegöl', 'İznik', 'Karacabey', 'Keles', 'Kestel', 'Mudanya', 'Mustafakemalpaşa', 'Nilüfer', 'Orhaneli', 'Orhangazi', 'Osmangazi', 'Yenişehir', 'Yıldırım'],
      canakkale: ['Ayvacık', 'Bayramiç', 'Biga', 'Bozcaada', 'Çan', 'Eceabat', 'Ezine', 'Gelibolu', 'Gökçeada', 'Lapseki', 'Merkez', 'Yenice'],
      cankiri: ['Atkaracalar', 'Bayramören', 'Çerkeş', 'Eldivan', 'Ilgaz', 'Kızılırmak', 'Korgun', 'Kurşunlu', 'Merkez', 'Orta', 'Şabanözü', 'Yapraklı'],
      corum: ['Alaca', 'Bayat', 'Boğazkale', 'Dodurga', 'İskilip', 'Kargı', 'Laçin', 'Mecitözü', 'Merkez', 'Oğuzlar', 'Ortaköy', 'Osmancık', 'Sungurlu', 'Uğurludağ'],
      denizli: ['Acıpayam', 'Babadağ', 'Baklan', 'Bekilli', 'Beyağaç', 'Bozkurt', 'Buldan', 'Çal', 'Çameli', 'Çardak', 'Çivril', 'Güney', 'Honaz', 'Kale', 'Merkezefendi', 'Pamukkale', 'Sarayköy', 'Serinhisar', 'Tavas'],
      diyarbakir: ['Bağlar', 'Bismil', 'Çermik', 'Çınar', 'Çüngüş', 'Dicle', 'Eğil', 'Ergani', 'Hani', 'Hazro', 'Kayapınar', 'Kocaköy', 'Kulp', 'Lice', 'Silvan', 'Sur', 'Yenişehir'],
      edirne: ['Enez', 'Havsa', 'İpsala', 'Keşan', 'Lalapaşa', 'Meriç', 'Merkez', 'Süloğlu', 'Uzunköprü'],
      elazig: ['Ağın', 'Alacakaya', 'Arıcak', 'Baskil', 'Karakoçan', 'Keban', 'Kovancılar', 'Maden', 'Merkez', 'Palu', 'Sivrice'],
      erzincan: ['Çayırlı', 'İliç', 'Kemah', 'Kemaliye', 'Merkez', 'Otlukbeli', 'Refahiye', 'Tercan', 'Üzümlü'],
      erzurum: ['Aşkale', 'Aziziye', 'Çat', 'Hınıs', 'Horasan', 'İspir', 'Karaçoban', 'Karayazı', 'Köprüköy', 'Narman', 'Oltu', 'Olur', 'Palandöken', 'Pasinler', 'Pazaryolu', 'Şenkaya', 'Tekman', 'Tortum', 'Uzundere', 'Yakutiye'],
      eskisehir: ['Alpu', 'Beylikova', 'Çifteler', 'Günyüzü', 'Han', 'İnönü', 'Mahmudiye', 'Mihalgazi', 'Mihalıççık', 'Odunpazarı', 'Sarıcakaya', 'Seyitgazi', 'Sivrihisar', 'Tepebaşı'],
      gaziantep: ['Araban', 'İslahiye', 'Karkamış', 'Nizip', 'Nurdağı', 'Oğuzeli', 'Şahinbey', 'Şehitkamil', 'Yavuzeli'],
      giresun: ['Alucra', 'Bulancak', 'Çamoluk', 'Çanakçı', 'Dereli', 'Doğankent', 'Espiye', 'Eynesil', 'Görele', 'Güce', 'Keşap', 'Merkez', 'Piraziz', 'Şebinkarahisar', 'Tirebolu', 'Yağlıdere'],
      gumushane: ['Kelkit', 'Köse', 'Kürtün', 'Merkez', 'Şiran', 'Torul'],
      hakkari: ['Çukurca', 'Derecik', 'Merkez', 'Şemdinli', 'Yüksekova'],
      hatay: ['Altınözü', 'Antakya', 'Arsuz', 'Belen', 'Defne', 'Dörtyol', 'Erzin', 'Hassa', 'İskenderun', 'Kırıkhan', 'Kumlu', 'Payas', 'Reyhanlı', 'Samandağ', 'Yayladağı'],
      isparta: ['Aksu', 'Atabey', 'Eğirdir', 'Gelendost', 'Gönen', 'Keçiborlu', 'Merkez', 'Senirkent', 'Sütçüler', 'Şarkikaraağaç', 'Uluborlu', 'Yalvaç', 'Yenişarbademli'],
      mersin: ['Akdeniz', 'Anamur', 'Aydıncık', 'Bozyazı', 'Çamlıyayla', 'Erdemli', 'Gülnar', 'Mezitli', 'Mut', 'Silifke', 'Tarsus', 'Toroslar', 'Yenişehir'],
      istanbul: ['Adalar', 'Arnavutköy', 'Ataşehir', 'Avcılar', 'Bağcılar', 'Bahçelievler', 'Bakırköy', 'Başakşehir', 'Bayrampaşa', 'Beşiktaş', 'Beykoz', 'Beylikdüzü', 'Beyoğlu', 'Büyükçekmece', 'Çatalca', 'Çekmeköy', 'Esenler', 'Esenyurt', 'Eyüpsultan', 'Fatih', 'Gaziosmanpaşa', 'Güngören', 'Kadıköy', 'Kağıthane', 'Kartal', 'Küçükçekmece', 'Maltepe', 'Pendik', 'Sancaktepe', 'Sarıyer', 'Silivri', 'Sultanbeyli', 'Sultangazi', 'Şile', 'Şişli', 'Tuzla', 'Ümraniye', 'Üsküdar', 'Zeytinburnu'],
      izmir: ['Aliağa', 'Balçova', 'Bayındır', 'Bayraklı', 'Bergama', 'Beydağ', 'Bornova', 'Buca', 'Çeşme', 'Çiğli', 'Dikili', 'Foça', 'Gaziemir', 'Güzelbahçe', 'Karabağlar', 'Karaburun', 'Karşıyaka', 'Kemalpaşa', 'Kınık', 'Kiraz', 'Konak', 'Menderes', 'Menemen', 'Narlıdere', 'Ödemiş', 'Seferihisar', 'Selçuk', 'Tire', 'Torbalı', 'Urla'],
      kars: ['Akyaka', 'Arpaçay', 'Digor', 'Kağızman', 'Merkez', 'Sarıkamış', 'Selim', 'Susuz'],
      kastamonu: ['Abana', 'Ağlı', 'Araç', 'Azdavay', 'Bozkurt', 'Cide', 'Çatalzeytin', 'Daday', 'Devrekani', 'Doğanyurt', 'Hanönü', 'İhsangazi', 'İnebolu', 'Küre', 'Merkez', 'Pınarbaşı', 'Seydiler', 'Şenpazar', 'Taşköprü', 'Tosya'],
      kayseri: ['Akkışla', 'Bünyan', 'Develi', 'Felahiye', 'Hacılar', 'İncesu', 'Kocasinan', 'Melikgazi', 'Özvatan', 'Pınarbaşı', 'Sarıoğlan', 'Sarız', 'Talas', 'Tomarza', 'Yahyalı', 'Yeşilhisar'],
      kirklareli: ['Babaeski', 'Demirköy', 'Kofçaz', 'Lüleburgaz', 'Merkez', 'Pehlivanköy', 'Pınarhisar', 'Vize'],
      kirsehir: ['Akçakent', 'Akpınar', 'Boztepe', 'Çiçekdağı', 'Kaman', 'Merkez', 'Mucur'],
      kocaeli: ['Başiskele', 'Çayırova', 'Darıca', 'Derince', 'Dilovası', 'Gebze', 'Gölcük', 'İzmit', 'Kandıra', 'Karamürsel', 'Kartepe', 'Körfez'],
      konya: ['Ahırlı', 'Akören', 'Akşehir', 'Altınekin', 'Beyşehir', 'Bozkır', 'Cihanbeyli', 'Çeltik', 'Çumra', 'Derbent', 'Derebucak', 'Doğanhisar', 'Emirgazi', 'Ereğli', 'Güneysınır', 'Hadim', 'Halkapınar', 'Hüyük', 'Ilgın', 'Kadınhanı', 'Karapınar', 'Karatay', 'Kulu', 'Meram', 'Sarayönü', 'Selçuklu', 'Seydişehir', 'Taşkent', 'Tuzlukçu', 'Yalıhüyük', 'Yunak'],
      kutahya: ['Altıntaş', 'Aslanapa', 'Çavdarhisar', 'Domaniç', 'Dumlupınar', 'Emet', 'Gediz', 'Hisarcık', 'Merkez', 'Pazarlar', 'Simav', 'Şaphane', 'Tavşanlı'],
      malatya: ['Akçadağ', 'Arapgir', 'Arguvan', 'Battalgazi', 'Darende', 'Doğanşehir', 'Doğanyol', 'Hekimhan', 'Kale', 'Kuluncak', 'Pütürge', 'Yazıhan', 'Yeşilyurt'],
      manisa: ['Ahmetli', 'Akhisar', 'Alaşehir', 'Demirci', 'Gölmarmara', 'Gördes', 'Kırkağaç', 'Köprübaşı', 'Kula', 'Salihli', 'Sarıgöl', 'Saruhanlı', 'Selendi', 'Soma', 'Şehzadeler', 'Turgutlu', 'Yunusemre'],
      kahramanmaras: ['Afşin', 'Andırın', 'Çağlayancerit', 'Dulkadiroğlu', 'Ekinözü', 'Elbistan', 'Göksun', 'Nurhak', 'Onikişubat', 'Pazarcık', 'Türkoğlu'],
      mardin: ['Artuklu', 'Dargeçit', 'Derik', 'Kızıltepe', 'Mazıdağı', 'Midyat', 'Nusaybin', 'Ömerli', 'Savur', 'Yeşilli'],
      mugla: ['Bodrum', 'Dalaman', 'Datça', 'Fethiye', 'Kavaklıdere', 'Köyceğiz', 'Marmaris', 'Menteşe', 'Milas', 'Ortaca', 'Seydikemer', 'Ula', 'Yatağan'],
      mus: ['Bulanık', 'Hasköy', 'Korkut', 'Malazgirt', 'Merkez', 'Varto'],
      nevsehir: ['Acıgöl', 'Avanos', 'Derinkuyu', 'Gülşehir', 'Hacıbektaş', 'Kozaklı', 'Merkez', 'Ürgüp'],
      nigde: ['Altunhisar', 'Bor', 'Çamardı', 'Çiftlik', 'Merkez', 'Ulukışla'],
      ordu: ['Akkuş', 'Altınordu', 'Aybastı', 'Çamaş', 'Çatalpınar', 'Çaybaşı', 'Fatsa', 'Gölköy', 'Gülyalı', 'Gürgentepe', 'İkizce', 'Kabadüz', 'Kabataş', 'Korgan', 'Kumru', 'Mesudiye', 'Perşembe', 'Ulubey', 'Ünye'],
      rize: ['Ardeşen', 'Çamlıhemşin', 'Çayeli', 'Derepazarı', 'Fındıklı', 'Güneysu', 'Hemşin', 'İkizdere', 'İyidere', 'Kalkandere', 'Merkez', 'Pazar'],
      sakarya: ['Adapazarı', 'Akyazı', 'Arifiye', 'Erenler', 'Ferizli', 'Geyve', 'Hendek', 'Karapürçek', 'Karasu', 'Kaynarca', 'Kocaali', 'Pamukova', 'Sapanca', 'Serdivan', 'Söğütlü', 'Taraklı'],
      samsun: ['19 Mayıs', 'Alaçam', 'Asarcık', 'Atakum', 'Ayvacık', 'Bafra', 'Canik', 'Çarşamba', 'Havza', 'İlkadım', 'Kavak', 'Ladik', 'Salıpazarı', 'Tekkeköy', 'Terme', 'Vezirköprü', 'Yakakent'],
      siirt: ['Baykan', 'Eruh', 'Kurtalan', 'Merkez', 'Pervari', 'Şirvan', 'Tillo'],
      sinop: ['Ayancık', 'Boyabat', 'Dikmen', 'Durağan', 'Erfelek', 'Gerze', 'Merkez', 'Saraydüzü', 'Türkeli'],
      sivas: ['Akıncılar', 'Altınyayla', 'Divriği', 'Doğanşar', 'Gemerek', 'Gölova', 'Gürün', 'Hafik', 'İmranlı', 'Kangal', 'Koyulhisar', 'Merkez', 'Suşehri', 'Şarkışla', 'Ulaş', 'Yıldızeli', 'Zara'],
      tekirdag: ['Çerkezköy', 'Çorlu', 'Ergene', 'Hayrabolu', 'Kapaklı', 'Malkara', 'Marmaraereğlisi', 'Muratlı', 'Saray', 'Süleymanpaşa', 'Şarköy'],
      tokat: ['Almus', 'Artova', 'Başçiftlik', 'Erbaa', 'Merkez', 'Niksar', 'Pazar', 'Reşadiye', 'Sulusaray', 'Turhal', 'Yeşilyurt', 'Zile'],
      trabzon: ['Akçaabat', 'Araklı', 'Arsin', 'Beşikdüzü', 'Çarşıbaşı', 'Çaykara', 'Dernekpazarı', 'Düzköy', 'Hayrat', 'Köprübaşı', 'Maçka', 'Of', 'Ortahisar', 'Sürmene', 'Şalpazarı', 'Tonya', 'Vakfıkebir', 'Yomra'],
      tunceli: ['Çemişgezek', 'Hozat', 'Mazgirt', 'Merkez', 'Nazımiye', 'Ovacık', 'Pertek', 'Pülümür'],
      sanliurfa: ['Akçakale', 'Birecik', 'Bozova', 'Ceylanpınar', 'Eyyübiye', 'Halfeti', 'Haliliye', 'Harran', 'Hilvan', 'Karaköprü', 'Siverek', 'Suruç', 'Viranşehir'],
      usak: ['Banaz', 'Eşme', 'Karahallı', 'Merkez', 'Sivaslı', 'Ulubey'],
      van: ['Bahçesaray', 'Başkale', 'Çaldıran', 'Çatak', 'Edremit', 'Erciş', 'Gevaş', 'Gürpınar', 'İpekyolu', 'Muradiye', 'Özalp', 'Saray', 'Tuşba'],
      yozgat: ['Akdağmadeni', 'Aydıncık', 'Boğazlıyan', 'Çandır', 'Çayıralan', 'Çekerek', 'Kadışehri', 'Merkez', 'Saraykent', 'Sarıkaya', 'Sorgun', 'Şefaatli', 'Yenifakılı', 'Yerköy'],
      zonguldak: ['Alaplı', 'Çaycuma', 'Devrek', 'Gökçebey', 'Karadeniz Ereğli', 'Kilimli', 'Kozlu', 'Merkez'],
      aksaray: ['Ağaçören', 'Eskil', 'Gülağaç', 'Güzelyurt', 'Merkez', 'Ortaköy', 'Sarıyahşi', 'Sultanhanı'],
      bayburt: ['Aydıntepe', 'Demirözü', 'Merkez'],
      karaman: ['Ayrancı', 'Başyayla', 'Ermenek', 'Kazımkarabekir', 'Merkez', 'Sarıveliler'],
      kirikkale: ['Bahşılı', 'Balışeyh', 'Çelebi', 'Delice', 'Karakeçili', 'Keskin', 'Merkez', 'Sulakyurt', 'Yahşihan'],
      batman: ['Beşiri', 'Gercüş', 'Hasankeyf', 'Kozluk', 'Merkez', 'Sason'],
      sirnak: ['Beytüşşebap', 'Cizre', 'Güçlükonak', 'İdil', 'Merkez', 'Silopi', 'Uludere'],
      bartin: ['Amasra', 'Kurucaşile', 'Merkez', 'Ulus'],
      ardahan: ['Çıldır', 'Damal', 'Göle', 'Hanak', 'Merkez', 'Posof'],
      igdir: ['Aralık', 'Karakoyunlu', 'Merkez', 'Tuzluca'],
      yalova: ['Altınova', 'Armutlu', 'Çınarcık', 'Çiftlikköy', 'Merkez', 'Termal'],
      karabuk: ['Eflani', 'Eskipazar', 'Merkez', 'Ovacık', 'Safranbolu', 'Yenice'],
      kilis: ['Elbeyli', 'Merkez', 'Musabeyli', 'Polateli'],
      osmaniye: ['Bahçe', 'Düziçi', 'Hasanbeyli', 'Kadirli', 'Merkez', 'Sumbas', 'Toprakkale'],
      duzce: ['Akçakoca', 'Cumayeri', 'Çilimli', 'Gölyaka', 'Gümüşova', 'Kaynaşlı', 'Merkez', 'Yığılca']
    };

    let globalId = 100;
    for (const p of TUR_PROVINCES) {
      const names = provincesDistrictNames[p.slug] || ['Merkez'];
      names.forEach((name, idx) => {
        const slug = name.toLowerCase().replace(/ğ/g, 'g').replace(/ü/g, 'u').replace(/ş/g, 's').replace(/ı/g, 'i').replace(/ö/g, 'o').replace(/ç/g, 'c').replace(/[^a-z0-9]/g, '-');
        const key = `${p.slug}-${slug}`;
        if (knownKeys.has(key)) return;
        globalId++;
        const angle = (idx / names.length) * 6.28318;
        const radius = 0.08 + (idx % 3) * 0.06;
        const lat = Math.round((p.center.lat + Math.sin(angle) * radius) * 10000) / 10000;
        const lon = Math.round((p.center.lon + Math.cos(angle) * radius) * 10000) / 10000;
        list.push({
          gid: `TUR.${p.plate_code}.${globalId}_1`,
          province_slug: p.slug,
          province_name: p.name,
          name,
          slug,
          center: { lat, lon },
          bbox: {
            min_lon: Math.round((lon - 0.05) * 10000) / 10000,
            min_lat: Math.round((lat - 0.05) * 10000) / 10000,
            max_lon: Math.round((lon + 0.05) * 10000) / 10000,
            max_lat: Math.round((lat + 0.05) * 10000) / 10000,
          },
          neighborhood_count: 10,
        });
      });
    }
    return list;
  })(),
];

export const TUR_NEIGHBORHOODS: GadmNeighborhood[] = [
  {
    gid: "TUR.34.18.1_1",
    province_slug: "istanbul",
    district_slug: "kadikoy",
    name: "Caferağa",
    slug: "caferaga",
    center: { lat: 40.987654, lon: 29.023456 },
    bbox: { min_lon: 29.015, min_lat: 40.98, max_lon: 29.035, max_lat: 40.995 },
    postal_code: "34710",
  },
  {
    gid: "TUR.34.18.2_1",
    province_slug: "istanbul",
    district_slug: "kadikoy",
    name: "Moda",
    slug: "moda",
    center: { lat: 40.983, lon: 29.025 },
    bbox: { min_lon: 29.018, min_lat: 40.978, max_lon: 29.03, max_lat: 40.988 },
    postal_code: "34710",
  },
  {
    gid: "TUR.34.18.3_1",
    province_slug: "istanbul",
    district_slug: "kadikoy",
    name: "Caddebostan",
    slug: "caddebostan",
    center: { lat: 40.965, lon: 29.06 },
    bbox: { min_lon: 29.05, min_lat: 40.955, max_lon: 29.075, max_lat: 40.975 },
    postal_code: "34728",
  },
  {
    gid: "TUR.34.18.4_1",
    province_slug: "istanbul",
    district_slug: "kadikoy",
    name: "Fenerbahçe",
    slug: "fenerbahce",
    center: { lat: 40.972, lon: 29.043 },
    bbox: { min_lon: 29.035, min_lat: 40.965, max_lon: 29.055, max_lat: 40.98 },
    postal_code: "34726",
  },
  {
    gid: "TUR.34.18.5_1",
    province_slug: "istanbul",
    district_slug: "kadikoy",
    name: "Suadiye",
    slug: "suadiye",
    center: { lat: 40.96, lon: 29.08 },
    bbox: { min_lon: 29.07, min_lat: 40.95, max_lon: 29.095, max_lat: 40.97 },
    postal_code: "34740",
  },
  {
    gid: "TUR.34.18.6_1",
    province_slug: "istanbul",
    district_slug: "kadikoy",
    name: "Bostancı",
    slug: "bostanci",
    center: { lat: 40.955, lon: 29.095 },
    bbox: { min_lon: 29.085, min_lat: 40.945, max_lon: 29.11, max_lat: 40.965 },
    postal_code: "34744",
  },
  {
    gid: "TUR.34.18.7_1",
    province_slug: "istanbul",
    district_slug: "kadikoy",
    name: "Acıbadem",
    slug: "acibadem",
    center: { lat: 41.002, lon: 29.045 },
    bbox: { min_lon: 29.035, min_lat: 40.995, max_lon: 29.06, max_lat: 41.01 },
    postal_code: "34718",
  },
  {
    gid: "TUR.34.18.8_1",
    province_slug: "istanbul",
    district_slug: "kadikoy",
    name: "19 Mayıs",
    slug: "19-mayis",
    center: { lat: 40.975, lon: 29.085 },
    bbox: { min_lon: 29.075, min_lat: 40.968, max_lon: 29.095, max_lat: 40.982 },
    postal_code: "34736",
  },
  {
    gid: "TUR.34.4.1_1",
    province_slug: "istanbul",
    district_slug: "besiktas",
    name: "Sinanpaşa",
    slug: "sinanpasa",
    center: { lat: 41.0428, lon: 29.0077 },
    bbox: { min_lon: 29.0, min_lat: 41.038, max_lon: 29.015, max_lat: 41.048 },
    postal_code: "34353",
  },
  {
    gid: "TUR.34.4.2_1",
    province_slug: "istanbul",
    district_slug: "besiktas",
    name: "Levent",
    slug: "levent",
    center: { lat: 41.078, lon: 29.015 },
    bbox: { min_lon: 29.005, min_lat: 41.07, max_lon: 29.028, max_lat: 41.088 },
    postal_code: "34330",
  },
  {
    gid: "TUR.34.4.3_1",
    province_slug: "istanbul",
    district_slug: "besiktas",
    name: "Etiler",
    slug: "etiler",
    center: { lat: 41.082, lon: 29.032 },
    bbox: { min_lon: 29.02, min_lat: 41.075, max_lon: 29.045, max_lat: 41.09 },
    postal_code: "34337",
  },
  {
    gid: "TUR.34.4.4_1",
    province_slug: "istanbul",
    district_slug: "besiktas",
    name: "Bebek",
    slug: "bebek",
    center: { lat: 41.076, lon: 29.043 },
    bbox: { min_lon: 29.035, min_lat: 41.068, max_lon: 29.055, max_lat: 41.085 },
    postal_code: "34342",
  },
  {
    gid: "TUR.34.4.5_1",
    province_slug: "istanbul",
    district_slug: "besiktas",
    name: "Ortaköy",
    slug: "ortakoy",
    center: { lat: 41.049, lon: 29.026 },
    bbox: { min_lon: 29.015, min_lat: 41.042, max_lon: 29.035, max_lat: 41.058 },
    postal_code: "34347",
  },
  {
    gid: "TUR.34.33.1_1",
    province_slug: "istanbul",
    district_slug: "sisli",
    name: "19 Mayıs",
    slug: "19-mayis",
    center: { lat: 41.0631, lon: 28.9925 },
    bbox: { min_lon: 28.985, min_lat: 41.058, max_lon: 29.002, max_lat: 41.07 },
    postal_code: "34360",
  },
  {
    gid: "TUR.34.33.2_1",
    province_slug: "istanbul",
    district_slug: "sisli",
    name: "Mecidiyeköy",
    slug: "mecidiyekoy",
    center: { lat: 41.066, lon: 28.995 },
    bbox: { min_lon: 28.988, min_lat: 41.06, max_lon: 29.005, max_lat: 41.075 },
    postal_code: "34387",
  },
  {
    gid: "TUR.34.33.3_1",
    province_slug: "istanbul",
    district_slug: "sisli",
    name: "Esentepe",
    slug: "esentepe",
    center: { lat: 41.072, lon: 29.008 },
    bbox: { min_lon: 29.0, min_lat: 41.065, max_lon: 29.018, max_lat: 41.08 },
    postal_code: "34394",
  },
  {
    gid: "TUR.34.33.4_1",
    province_slug: "istanbul",
    district_slug: "sisli",
    name: "Fulya",
    slug: "fulya",
    center: { lat: 41.056, lon: 28.999 },
    bbox: { min_lon: 28.99, min_lat: 41.05, max_lon: 29.01, max_lat: 41.065 },
    postal_code: "34394",
  },
  {
    gid: "TUR.48.1.1_1",
    province_slug: "mugla",
    district_slug: "bodrum",
    name: "Köy İçi",
    slug: "koy-ici",
    center: { lat: 37.0345, lon: 27.4305 },
    bbox: { min_lon: 27.42, min_lat: 37.025, max_lon: 27.445, max_lat: 37.045 },
    postal_code: "48400",
  },
  {
    gid: "TUR.48.1.2_1",
    province_slug: "mugla",
    district_slug: "bodrum",
    name: "Çarşı",
    slug: "carsi",
    center: { lat: 37.035, lon: 27.428 },
    bbox: { min_lon: 27.42, min_lat: 37.028, max_lon: 27.436, max_lat: 37.042 },
    postal_code: "48400",
  },
  {
    gid: "TUR.48.1.3_1",
    province_slug: "mugla",
    district_slug: "bodrum",
    name: "Yalıkavak",
    slug: "yalikavak",
    center: { lat: 37.106, lon: 27.294 },
    bbox: { min_lon: 27.27, min_lat: 37.085, max_lon: 27.32, max_lat: 37.125 },
    postal_code: "48990",
  },
  {
    gid: "TUR.48.1.4_1",
    province_slug: "mugla",
    district_slug: "bodrum",
    name: "Turgutreis",
    slug: "turgutreis",
    center: { lat: 37.001, lon: 27.26 },
    bbox: { min_lon: 27.24, min_lat: 36.98, max_lon: 27.285, max_lat: 37.025 },
    postal_code: "48960",
  },
  {
    gid: "TUR.6.7.1_1",
    province_slug: "ankara",
    district_slug: "cankaya",
    name: "Kızılay",
    slug: "kizilay",
    center: { lat: 39.9208, lon: 32.8541 },
    bbox: { min_lon: 32.845, min_lat: 39.915, max_lon: 32.865, max_lat: 39.928 },
    postal_code: "06420",
  },
  {
    gid: "TUR.6.7.2_1",
    province_slug: "ankara",
    district_slug: "cankaya",
    name: "Gaziosmanpaşa",
    slug: "gaziosmanpasa",
    center: { lat: 39.897, lon: 32.868 },
    bbox: { min_lon: 32.855, min_lat: 39.888, max_lon: 32.88, max_lat: 39.905 },
    postal_code: "06700",
  },
  {
    gid: "TUR.6.7.3_1",
    province_slug: "ankara",
    district_slug: "cankaya",
    name: "Çayyolu",
    slug: "cayyolu",
    center: { lat: 39.882, lon: 32.695 },
    bbox: { min_lon: 32.67, min_lat: 39.865, max_lon: 32.72, max_lat: 39.9 },
    postal_code: "06810",
  },
  {
    gid: "TUR.35.20.1_1",
    province_slug: "izmir",
    district_slug: "konak",
    name: "Alsancak",
    slug: "alsancak",
    center: { lat: 38.438, lon: 27.142 },
    bbox: { min_lon: 27.132, min_lat: 38.43, max_lon: 27.155, max_lat: 38.448 },
    postal_code: "35220",
  },
  {
    gid: "TUR.35.20.2_1",
    province_slug: "izmir",
    district_slug: "konak",
    name: "Göztepe",
    slug: "goztepe",
    center: { lat: 38.398, lon: 27.098 },
    bbox: { min_lon: 27.085, min_lat: 38.39, max_lon: 27.11, max_lat: 38.408 },
    postal_code: "35290",
  },
];
